linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
  disable-all: true

linters-settings:
  govet:
    check-shadowing: true

run:
  go: '1.24'
  timeout: 5m
  skip-dirs:
    - internal/mocks
