version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
  exclusions:
    paths:
      - internal/mocks

run:
  go: "1.24"
  timeout: 5m
  allow-parallel-runners: true
